name: Deployment workflow
  
on:
  push: 
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - run : |
          curl https://get.okteto.com -sSfL | sh
          okteto version
          okteto context
          node -v
        
    
  
  
