name: Deployment workflow
  
on:
  push: 
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |

          cd server
          echo "${{ secrets.SERVER_ENV_FILE }}" > .env
          okteto deploy --build
          
          cd ../client
          echo "${{ secrets.CLIENT_ENV_FILE }}" > .env
          okteto deploy --build
    
          
          
    
  
  
