name: Deployment workflow
  
on:
  push: 
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |

          cd server
          echo "${{ secrets.SERVER_ENV_FILE }}"  .env
          ls
          cat .env
    
          
          
    
  
  
